config/routes.rb
Rails.application.routes.draw do
  resources :post_comments
  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
  get 'categories/index'

  get 'categories/new'

  get 'categories/edit'

  get 'categories/show'

  root :to => 'home#index'
    resources :posts 
    resources :categories
    match '/about', :to => 'pages#about', via: :all
    match '/contact', :to => 'pages#contact', via: :all
    match '/resources', :to => 'pages#resources', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :admin_user
  has_many :post_comments, :dependent => :delete_all
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post

  validates_presence_of :name
  validates_length_of :name, minimum:2, maximum:20
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :all_categories
  before_action :site_search

  def all_categories
  	@categories = Category.all
  end

  def all_posts
  	@posts = Post.all  	
  end

  def site_search
  	@q = Post.ransack(params[:q])
  	@search_posts = @q.result
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
  end

 end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@post = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base

  def create
    @post_comment = PostComment.new(params.require(:post_comment).permit(:name, :email, :body, :post_id))
    if @post_comment.save
     	flash[:notice] = "Comment was sucessfully created."
     	redirect_to(@post_comment.post)
    else
    	flash[:notice] = "Error creating post_comment: #{@post_comment.errors}"
     	redirect_to(@post_comment.post)
      end
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @q = Post.ransack(params[:q])
    @post = @q.result
  end

  def show
    @post = Post.find(params[:id])
    @user = AdminUser.all
    @post_comment = PostComment.new(:post => @post)
  end

  def new
    @post = Post.new
    @category = Category.all
  end

  def create
    @post = Post.new(params.require(:post).permit(:title,:body,:category_id))
    if @post.save
      redirect_to posts_path, :notice => "Your post has been saved"
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params.require(:id))
    if @post.update_attributes(params.require(:post).permit(:title,:body,:category_id))
      redirect_to post_path, :notice => "Your post has been updated"
    else
        render "edit"
    end 
  end 

  def destroy
    @post = Post.find(params.require(:id))
    @post.destroy!
    redirect_to posts_path, :notice => "Your post has been deleted"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
  <ul>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, category %></li>
    <% end %>
  <ul>
  

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% if @posts.each do |post| %>
	<h3><%= link_to post.title, post %></h3>
	<p><%= post.body %></p>
<% end.empty? %>
	<p>Sorry, there are no posts in this category</p>
<% end %>
	<%= link_to "Back to Categories", 	categories_path %>

app/views/home/index.html.erb
<% @post.each do |post| %>
	<div class="post">
  	<h2 class="title"><%= link_to post.title,post %></h2>
   	<div class="entry"><%= post.body%></div>
   	<div class="byline">
   		<p class="meta"> May 07, 2012 Posted by <%= post.admin_user.name %></p>
   		<p class="links"><%= link_to "Read More",post %></p>
  	</div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
  <div id="page">
    <div id="page-bgtop">
      <div id="page-bgbtm">
        <div id="content">
          <div class="flash-message">
            <% flash.each do |key,value| %>
              <p><%= value %></p>
            <% end %>
          </div>
            <%= yield %><!-- main view -->
            <div>&nbsp;</div>
        </div>
        <!-- end # content -->
       <%= render "partials/sidebar" %>
        <div style="clear: both">&nbsp;</div>
        
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrubyblog</title>
    <link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div id="wrapper">
    <div id="header-wrapper">
      <div id="header">
        <div id="logo">
          <h1><a href="#">My Ruby Blog</a></h1>
          <p>Learning Ruby on Rails</p>
        </div>
              <div id="menu">
                <ul class="main-nav">
                  <li><%= link_to "Home", root_path %></li>
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "Blog", posts_path %></li>
                  <li><%= link_to "Contact", contact_path %></li>
                  <li><%= link_to "Resources", resources_path %></li>
                </ul>
              </div>
      </div>
    </div>
  </div>

  <!-- end # header -->

app/views/partials/_post_comment.html.erb
<div class="post_comment">
	<i><%=h post_comment.name %> says:</i><br />
	<%= simple_format h(post_comment.body) %>
</div>

app/views/partials/_sidebar.html.erb
 <div id="sidebar">
          <ul>
            <li>
              <div id="search">
                <%= search_form_for @q do |f| %>
                <%= f.text_field :title_or_body_contains %>
                <%= f.submit "Search" %>
                <% end %> 
              </div>
              <div style="clear: both;">&nbsp;</div>
            </li>
            <li>
              <h2>Categories</h2>
              <ul>
                <% all_categories.each do |cat| %>
                  <li><%= cat.name %></li>
                <% end %>
              </ul>
            </li>
            <li>
              <h2>Blogroll</h2>
              <ul>
                <li><a href="#">Blog Post</a></li>
                <li><a href="#">Blog Post</a></li>
                <li><a href="#">Blog Post</a></li>
                <li><a href="#">Blog Post</a></li>
                <li><a href="#">Blog Post</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- end of #sidebar -->

app/views/posts/index.html.erb
<% @post.each do |post| %>
<div class="post">
   <h2><%= link_to post.title,post %></h2>
   <div class="entry"><%= post.body%></div>
   <div class="byline">
   		<p class="meta"> May 07, 2012 Posted by <%= post.admin_user.name %></p>
   		<p class="links"><%= link_to "Read More",post %></p>
  	</div>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="post"<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d %Y") %></small>
<p>Created by: <%= @post.admin_user.name %></p>
<p><%= @post.body %></p>
<p>Category: <%= link_to @post.category.name, category_path(:id => @post.category.id) %></p>
<p><%= link_to "Back", posts_path %></p>
<hr />
<h3>Ad Comment </h3>
<%= form_for @post_comment do |f| %>
	<%= f.hidden_field :post_id %>

	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit "Post Comment" %>
	</p>
<% end %>

<%= render partial: 'partials/post_comment', :collection => @post.post_comments %>
</div>